### ISSUE TITLE
Uncaught error on startup

### ISSUE THREAD

**Issue by TheStigh** [kagjerde/MMM-Avinor#1]
Hi,  

I've installed the module today using default config.js settings.
Get following error in dev console:

main.js:394 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

Any ideas?

Hilsen fra Nordens Paris :)

**Comment by kagjerde** [comment]
Hi, 

I have tried to recreate your problem, but have not been able to get the same result.
Have you tried with the default Avinor URL? It can be that the reply for your ariport is different and there is a problem parsing it. 

If the problem crashes the module, then please give some more information of how you tested it.

Please note that i have cleaned up the code today, but even before this I did not get any errors.

Hilsen Kjell

**Comment by TheStigh** [comment]
Hei Kjell :)

Last commit fixed the issue.
Suggestion; could you do a check - if using in fullscreen separate Dep and Arr better?
I can do it myself, but it would be better to have this option for everybody :)

Closing topic.

Bra ide dette :) Vi må få til mer norsk på MM!
Slipper egen modul snart, blir en bra voice offline-modul med kjekke funksjoner.

**Comment by kagjerde** [comment]
Please see new layout in the latest commit in separate folder, there are now 3 options to change between CSS files. I found it easier to change between CSS's, than to change the code.
