### ISSUE TITLE
In combination with other module, gives Uncaught Expectaion 'toLowerCase'

### ISSUE THREAD

**Issue by TheStigh** [kagjerde/MMM-Avinor#2]
Hi Kjell,

In combination with a voice control module, this module creates an Uncaught Expectation when a voice command is issued. The message is 'toLowerCase'.

Perhaps we should discuss this, might happen in comvination with other modules also?

/Stigh

**Comment by kagjerde** [comment]
Hi, I am not an expert of debugging in MM, but have not found any reference to the fault message. But I will investigate further, but please feel free to contribute in any way. I will update the code if required.

Kjell

**Comment by kagjerde** [comment]
I have made some changes, so that the CSS entries are not duplicated from other modules. 
Please see if this works better. 

Kjell

**Comment by kagjerde** [comment]
Closed
